language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.1

env:
    global:
        - TEST_COMMAND="./vendor/bin/phpunit"

branches:
    except:
        - /^analysis-.*$/

before_install:
    - iphpenv config-rm xdebug.ini || true

install:
    - travis_retry composer update --prefer-dist --no-interaction

script:
    - $TEST_COMMAND --testsuite Guzzle
    - $TEST_COMMAND --testsuite Zend
    - $TEST_COMMAND --testsuite Slim
